outdir: runs

model:
  batch_norm: False
  model: FCNN_local
  layers: [3,512,512,1]
  K: [5,5,5]

data:
  data_path: ../data/data_reactiva/uniforme_07_13_red30
  red: '30'
  normalize_X: True
  normalize_Y: False

training:
  device: 'cuda'
  batch_size: 64
  lr: 1e-4
  num_epochs: 500
  early_stopping: 30
  betas: [0.9, 0.999]
  weight_decay: 0
  seed: 42
