outdir: runs

model:
  batch_norm: False
  model: GNN_global
  layers: [3,512,512,1]
  K: [5,5,5]

data:
  data_path: ../data/data_reactiva/uru
  target: 'q_switch_shunt_opt'
  red: 'uru'
  red_path: '/home/iboero/grafos_proyecto/uy_pp_net_v13_(sin_eolico_ni_solar).p'
  normalize_X: False
  normalize_Y: False

training:
  device: 'cuda'
  batch_size: 128
  lr: 1e-3
  num_epochs: 500
  early_stopping: 30
  betas: [0.9, 0.999]
  weight_decay: 0
  seed: 42
  initial_metric_epoch: 501
  metric_frec: 501
