outdir: runs

model:
  batch_norm: True # Booleano
  model: GNN_global # Puede ser GNN_local, GNN_global, FCNN_glocal, FCNN_global
  layers: [3, 1024, 1024, 1] # La ultima dimension
  K: [4, 4, 4]

data:
  data_path: ../data/data_reactiva/uru
  target: 'q_switch_shunt_opt' # vm_pu_opt o q_switch_shunt_opt
  # data_path: ../data/data_reactiva/uniforme_07_13_red118
  red: 'uru' # 30 o 118 o uru
  red_path: '/home/iboero/grafos_proyecto/uy_pp_net_v13_(sin_eolico_ni_solar).p' # If 30 or 118 set to None, else path to pickle network
  normalize_X: False
  normalize_Y: False

training:
  device: 'cuda'
  batch_size: 128
  lr: 1e-4
  num_epochs: 500
  early_stopping: 30
  betas: [0.9, 0.999]
  weight_decay: 0
  seed: 42
  metric_frec: 501
  initial_metric_epoch: 501