outdir: runs
model:
  batch_norm: true
  model: GNN_local
  layers:
  - 2
  - 64
  - 128
  - 1
  K:
  - 4
  - 4
  - 4
data:
  data_path: /home/tomas/Desktop/GNN4OPF/data/data_nueva/uniforme_07_13_red30
  red: '30'
  normalize_X: true
  normalize_Y: false
  PQVd: false
training:
  device: cuda
  batch_size: 64
  lr: 0.001
  num_epochs: 300
  early_stopping: 30
  betas:
  - 0.9
  - 0.999
  weight_decay: 0
  seed: 42
