outdir: runs

model:
  batch_norm: True # Booleano
  model: GNN_local # Puede ser GNN_local, GNN_global, FCNN_glocal, FCNN_global
  layers: [2, 64, 128, 1] # La ultima dimension
  K: [4, 4, 4]

data:
  data_path: ../data/data_nueva/uniforme_07_13_red118
  red: '118' # 30 o 118
  normalize_X: True
  normalize_Y: False
  PQVd: False # Si es False, cambiar layers[0] a 2, sino vale 4

training:
  device: 'cuda'
  batch_size: 128
  lr: 1e-3
  num_epochs: 500
  early_stopping: 30
  betas: [0.9, 0.999]
  weight_decay: 0
  seed: 42
  