outdir: runs
model:
  batch_norm: true
  model: GNN_local
  layers:
  - 3
  - 64
  - 128
  - 1
  K:
  - 4
  - 4
  - 4
data:
  data_path: ../data/data_reactiva/uniforme_07_13_red118
  red: '118'
  normalize_X: true
  normalize_Y: true
training:
  device: cuda
  batch_size: 128
  lr: 0.0001
  num_epochs: 500
  early_stopping: 30
  betas:
  - 0.9
  - 0.999
  weight_decay: 0
  seed: 42
  metric_frec: 30
  initial_metric_epoch: 0
