outdir: ../resultados/runs_06-24
model:
  batch_norm: true
  model: GNN_local
  layers:
  - 3
  - 512
  - 512
  - 1
  K:
  - 5
  - 5
  - 5
data:
  data_path: ../data/red118/
  red: '118'
  normalize_X: true
  normalize_Y: false
training:
  device: cuda
  batch_size: 64
  lr: 7.967281183507415e-05
  num_epochs: 500
  early_stopping: 30
  betas:
  - 0.9
  - 0.999
  weight_decay: 0
  seed: 42
  metric_frec: 30
  initial_metric_epoch: 0
